org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.1
group=me.broodyr.headlampify

# Dependencies
fabric_api_version=0.161.0+26.3

# Optional compatibility (compile-only)
sodium_version=mc26.3-0.9.2-fabric
